apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echo
spec:
  gateways:
  - echo-gateway
  hosts:
  - "*"
  http:
  - name: primary
    route:
    - destination:
        host: echo-stable
        subset: stable
      weight: 0
    - destination:
        host: echo-canary
        subset: canary
      weight: 100
