apiVersion: v1
kind: Namespace
metadata:
  name: tenant-alpha
  labels:
    tenant: alpha
---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-beta
  labels:
    tenant: beta
---
# Simulated monitoring namespace (if not exists)
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    purpose: monitoring
---
# Frontend pod in tenant-alpha
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: tenant-alpha
  labels:
    app: frontend
    tier: web
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
---
# Backend pod in tenant-alpha
apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: tenant-alpha
  labels:
    app: backend
    tier: api
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 8080
    - containerPort: 9090
---
# Pod in tenant-beta (should be isolated)
apiVersion: v1
kind: Pod
metadata:
  name: workload
  namespace: tenant-beta
  labels:
    app: workload
spec:
  containers:
  - name: nginx
    image: nginx:alpine
