apiVersion: v1
kind: Namespace
metadata:
  name: cnpe-tracing-test
---
# Jaeger all-in-one collector is pre-deployed
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: cnpe-tracing-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.53
          ports:
            - containerPort: 16686
            - containerPort: 4317
            - containerPort: 4318
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: cnpe-tracing-test
spec:
  selector:
    app: jaeger
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: cnpe-tracing-test
spec:
  selector:
    app: jaeger
  ports:
    - port: 16686
      targetPort: 16686
# Task: Create order-service deployment with correct OTEL configuration
