apiVersion: v1
kind: Namespace
metadata:
  name: cnpe-incident-test
---
# Broken deployment - image tag doesn't exist
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor
  namespace: cnpe-incident-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-processor
  template:
    metadata:
      labels:
        app: order-processor
    spec:
      containers:
        - name: processor
          image: nginx:99.99-nonexistent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
# Task: Diagnose why pods are failing and fix the deployment
